### PR TITLE
grattan arrow + test added 

### PR DESCRIPTION
**Pull request by lachlanfox**
Hopefully actually works this time

### CODE REVIEW

**Comment by MattCowgill** [comment]
you just gonna leave old m8 hanging @wfmackey

**Comment by MattCowgill** [comment]
bloody kept you waiting hey @lachlanfox

**Comment by wfmackey** [comment]
@lachlanfox you can use this link to ban @MattCowgill from commenting on any `grattan/` repos just fri https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization

**Comment by MattCowgill** [comment]
@lachlanfox you can click the little smiley face on any of @wfmackey's comments to add the little rocket emoji or some googley eyes FYI

**Pull request merged**
