### PR TITLE
add export_latex_code

### PR DESCRIPTION
**Pull request by wfmackey**
sorry I added `stringr` as a dependency. Happy to switch to base regex functions if you want to avoid that.

### CODE REVIEW

**Comment by MattCowgill** [comment]
I just caught the branch up to master -- I'll wait to make sure it passes Travis

**Comment by MattCowgill** [comment]
& all good re `stringr`, I'm happy to assume that users of `grattantheme` have the `tidyverse` installed, in which case they already have `stringr`

**Comment by MattCowgill** [comment]
Do we want it to throw an error when there's no source/notes? 

```
> devtools::load_all(".")
Loading grattantheme
> library(ggplot2)
> p <- ggplot(mtcars,
+             aes(x = wt, y = mpg)) +
+   geom_point()
> p
> export_latex_code(p)
No title
No units
No notes or source provided.
Error in paste0("\\begin{figure}\n", "\t\\caption{", title, "\\label{fig:",  : 
  object 'caption_code' not found
```

**Comment by wfmackey** [comment]
Nah I don't think so -- sometimes you might be waiting on the notes/source. A message is fine?

**Comment by MattCowgill** [comment]
Yep, message is fine + good, but it's giving me a message AND an error.

Separate point: should the file path in `\includegraphics{}` reflect the actual file name the user has given to `grattan_save()`? Maybe that's getting a bit elaborate

**Comment by MattCowgill** [comment]
Looks like it's now failing because `clipr` on Linux requires some other (OS) package to be installed -- here's the Travis YAML file for `clipr` itself. I'll have more of a look later on https://github.com/mdlincoln/clipr/blob/master/.travis.yml

**Comment by wfmackey** [comment]
Bah, sorry. I’ll look into it later.

**Comment by wfmackey** [comment]
> Yep, message is fine + good, but it's giving me a message AND an error.

That was unintentional. Fixed now.

> Separate point: should the file path in `\includegraphics{}` reflect the actual file name the user has given to `grattan_save()`? Maybe that's getting a bit elaborate

Yep good idea. Added so that the filename is extracted from `path/to/save_file.pdf` and added to `atlas/save_file.pdf`in the `\includegraphics` call.

**Comment by MattCowgill** [comment]
awesome, cheers

**Comment by MattCowgill** [comment]
@wfmackey Rather than endless Travis-wrangling, I've decided to skip any tests on Travis that involve using the clipboard. I still test the LaTeX function on Travis, but just test the value it returns rather than the value it outputs to clipboard

**Pull request merged**
